---
all:
  children:
    local:
      hosts:
        localhost:
          ansible_connection: local
    
    linux:
      hosts:
        rhel9:
          ansible_host: 192.168.50.226

    k8s:
      hosts:
        controller:
          ansible_host: 192.168.50.232
        worker_app:
          ansible_host: 192.168.50.233 
        worker_logging:
          ansible_host: 192.168.50.234
