---
all:
  children:
    local:
      hosts:
        localhost:
          ansible_connection: local

    wind:
      hosts:
        192.168.50.135:

    linuxs:
      hosts:
        rhel9:
          ansible_host: 192.168.50.226
