---
    - name: "1/3 Update System"
      ansible.builtin.package:
        name: '*'
        state: latest 
    - name: Print all gathered facts
      ansible.builtin.debug:
        var: ansible_facts
    - name: "2/3 Install Packages  {{ packages_to_install }}"
      ansible.builtin.package:
        name: "{{ packages_to_install }}"
        state: present
    - name: "3/3 Get starship install script"
      ansible.builtin.shell:
        cmd: "curl -sS https://starship.rs/install.sh > {{ main_User_Home_Linx }}/startshup_install.sh"